### PR TITLE
Fix deps mismatch between AM and AT, refs #11363

### PR DESCRIPTION
**Pull request by jraddaoui**
- Pin up dependencies in common with AM: Bootstrap, jQuery and jQuery UI
- Upgrade jQuery UI to v1.12.1 (v1.11.4 used in AM is missing in Nodejs)
- Avoid importing jQuery in scripts (use jQuery instead of $) and in the Webpack
  embeddable entry
- Other clean ups in Webpack entries:
  - Move common parts to app.js
  - Remove import of missing Bootstrap and Fontawesome style files

### CODE REVIEW

**Comment by jraddaoui** [comment]
I doubt the standalone option was working and I think it's unnecessary since this app requires AM >1.6 and it's included in it. I'd like to know a second opinion about removing that feature completely or keeping it as it is to fix it in the future.

**Review by sevein — CHANGES_REQUESTED** [review]
I've suggested in https://github.com/artefactual/archivematica/pull/678 to include the sources of this repo in the Dashboard.

**Review by sevein — APPROVED** [review]
I'm personally fine removing the standalone entry because I've never used it and it may become less relevant once this repo is merged into the dashboard tree.  I'm not very familiar with some of the changes you're making in this pull request but this has been sitting here for 27 days so I suspect the only way to make progress is to merge. Thanks, @jraddaoui!

I'm hoping once the appraisal tab and the transfer browser trees are merged (https://github.com/artefactual/archivematica/pull/678) and simplify the development workflow I can learn more about how this application works.

**Comment by jraddaoui** [comment]
Thanks Sevein! This (specially the last commit) is only needed here because it needs to be added to AM stable/1.6.x

**Pull request merged**
