### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by Hwesta**
Move things around and make them look prettier.

Note this upgrades from bootstrap 1.4 (what Archivematica uses) to 3.3 (current version). This could be a problem when we want to integrate with the rest of Archivematica.

Colors are bootstrap default, and flexible.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Whee, this looks much nicer!

**Comment by mistydemeo** [comment]
Maybe the tab box on the right could use some hard edges?

screen shot 2015-07-15 at 10 15 52 am

**Comment by mistydemeo** [comment]
The "preview" tab box is a bit crowded with that many large tabs; as a next step, maybe it makes sense to constrain the size of the element and add a scroll bar.

**Comment by mistydemeo** [comment]
> This could be a problem when we want to integrate with the rest of Archivematica.

This is a good kick to get us to upgrade Archivematica, I think.

**Comment by mistydemeo** [comment]
I think this is a good start for getting feedback from the client tomorrow. :+1:

**Comment by Hwesta** [comment]
> Maybe the tab box on the right could use some hard edges?

It now draws the outline of the unselected tabs. Is that what you meant?

> The "preview" tab box is a bit crowded with that many large tabs; as a next step, maybe it makes sense to constrain the size of the element and add a scroll bar.

Not sure what you mean by many large tabs.  Too many rows?  Do we want to make the whole appraisal tab always fit on screen and scroll within panels?

**Comment by mistydemeo** [comment]
>  Too many rows?

Yeah - the tabs for filenames are the full width of the window, which is fine, but it means that large selections end up with huge numbers of files. Thinking two things to improve that: make it scroll within a fixed-size box, and add a type-in `<select>` to filter the list.

>  Do we want to make the whole appraisal tab always fit on screen and scroll within panels?

That's probably a good long-term goal, though maybe not within the scope of this PR.

**Comment by mistydemeo** [comment]
> It now draws the outline of the unselected tabs. Is that what you meant?

That's an improvement! It does look a bit off on a smaller monitor where it wraps though - maybe the tab box itself needs an outline, rather than complete for each individual tab.

screen shot 2015-07-15 at 11 20 10 am

**Comment by Hwesta** [comment]
Added index2.html with an alternate nav menu that probably wraps better. I think I like the tabs better though, even with wrapping issues.

**Pull request merged**
