### PR TITLE
More panes

### PR DESCRIPTION
**Pull request by Hwesta**
Convert UI to use movable, horizontally-resizable panes.  Put ArchivesSpace into its own pane.

No minimize functionality yet, and still buggy around resizing vs auto expanding for the content inside.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Do you think it would be feasible to make it clearer in the UI what is or is not draggable?

The headers are very small now on laptop screen sizes. When the tabs in the middle pane take up multiple rows, it's ambiguous what is or isn't a draggable portion of the frame. Screenshot below.

screen shot 2015-07-24 at 3 14 25 pm

**Comment by Hwesta** [comment]
Added light background for tabs.

**Comment by mistydemeo** [comment]
Did you push the updated branch?

**Comment by Hwesta** [comment]
Apparently not? Just did.  Might update this to use CSS resize instead of JS.

**Comment by Hwesta** [comment]
JQueryUI's resizable didn't behave well when the content inside was expanding.  CSS resize worked great, but did play well with JQueryUI's draggable.

New approach: Instead of resizable and draggable, display all tabs but be able to hide them.  Added a view/hide bar, which hides or displays the appropriate panel when clicked.  Panels automatically resize to fit the screen when added/removed.

**Comment by mistydemeo** [comment]
Looks good!

The default view is a bit cluttered with all panes open; maybe default to backlog and analysis being open and access system being closed?

**Comment by Hwesta** [comment]
> The default view is a bit cluttered with all panes open; maybe default to backlog and analysis being open and access system being closed?

Done

**Comment by mistydemeo** [comment]
:+1:

**Pull request merged**
