### PR TITLE
Replace jqTree

### PR DESCRIPTION
**Pull request by mistydemeo**
This replaces all uses of jqTree with angular-tree-control, and includes a vendored copy of that library in the repo.

There are a few advantages to this over jqTree for our uses:
- It's much easier to alter data and rerender the tree; the tree is watching the data using Angular's watch cycle, so simply altering the data causes the tree to rerender without any extra work.
- angular-tree-control has builtin support for filtering the tree via arbitrary functions, so it should be much easier to implement filtering of the tree; this was looking thorny in jqTree.
- Customizing how tree elements are rendered is much easier in angular-tree-control, which will be important when tagging is implemented.

### CODE REVIEW

**Comment by mistydemeo** [comment]
There's one outstanding bug in this version; selecting directories does select files, but they don't look selected in the UI. Should be a simple enough fix.

**Comment by mistydemeo** [comment]
A second benefit: it was trivial to implement #5 using this, whereas it was very difficult doing so in jqTree.

**Comment by Hwesta** [comment]
:+1:

**Comment by mistydemeo** [comment]
Merged!

**Pull request merged**
