### PR TITLE
Preview: get file data from File if not in FileList

### PR DESCRIPTION
**Pull request by mistydemeo**
The file data requested may not be located in the FileList. This happens if, for example, the user is visiting the appraisal tab from a link to the preview pane which contains a file UUID; the FileList will be empty in this case.

This still fetches the file from the FileList where possible, but will fall back to fetching it from the server otherwise.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Sorry for the giant diff; had to update the fixtures. The relevant part is here:

``` diff
--- a/app/preview/preview.controller.js
+++ b/app/preview/preview.controller.js
@@ -3,14 +3,27 @@
 (function() {
   angular.module('previewController', ['route-segment', 'fileListService']).

-  controller('PreviewController', ['$scope', '$routeSegment', 'FileList', function($scope, $routeSegment, FileList) {
+  controller('PreviewController', ['$scope', '$routeSegment', 'File', 'FileList', function($scope, $routeSegment, File, FileList) {
+    var vm = this;
+
+    vm.set_file_data = function(file) {
+      $scope.file = file;
+      $scope.url = 'fixtures/content/' + file.title;
+    };
+
     $scope.$routeSegment = $routeSegment;
     $scope.id = $routeSegment.$routeParams.id;
     if ($scope.id !== undefined) {
+      // Try to get file from the file list first, to avoid pinging the server.
       var file = FileList.get($scope.id);
       if (file) {
-        $scope.file = file;
-        $scope.url = 'fixtures/content/' + file.title;
+        vm.set_file_data(file);
+      } else {
+        // If the data isn't available, contact the server to fetch file info;
+        // it may not have been loaded.
+        File.get($scope.id).then(function (file) {
+          vm.set_file_data(file);
+        });
       }
     }
   }]);
```

**Comment by Hwesta** [comment]
:+1: 

While you're updating fixture data, maybe bring the file/*.json up to date with what's in transfers.json?  `bulk_extractor_reports`, `tags` and `group` are missing. Or wait until it's needed/we have a real backend?

**Comment by mistydemeo** [comment]
Updated the rest of the fixture data.

**Comment by Hwesta** [comment]
:+1: 

Though, on rebase you'll have to add format groups to the file info since #62 went in first.

**Pull request merged**
