### PR TITLE
Replace bower with webpack

### PR DESCRIPTION
**Pull request by mistydemeo**
This replaces bower with webpack, in order to produce a single bundled .js file which contains the entire appraisal tab and all of its dependencies. This greatly simplifies including the appraisal tab in other HTML pages, e.g. to help us integrate it with Django more easily.

This makes a few major changes:
- All dependencies are now installed using npm instead of bower.
- [Babel](http://babeljs.io) has been introduced to the build phase, allowing ES6 features to be used in the appraisal tab; modules are transpiled to browser-compatible JS during the pack phase. Currently, only ES6 `import` statements are used, but in the future other features could be used too.
- External, non-Archivematica dependencies now no longer use global names and instead depend on explicit `import` statements within each file. Since Angular has its own module system, there hasn't been much change to how the appraisal tab itself works, and I haven't begun converting any code from other parts of Archivematica to use modules.
- Non-JavaScript resources (CSS, images, webfonts, Angular partials) are also bundled into the same file; it's not necessary for the appraisal tab to fetch any of those separately. The bundling of Angular partials also means that Django routing doesn't break the appraisal tab.

### CODE REVIEW

**Comment by mistydemeo** [comment]
There are currently two failing tests, for reasons I'm not quite certain about:

```
Chrome 47.0.2526 (Mac OS X 10.11.2) ArchivesSpace should be able to fetch the levels of description FAILED
    TypeError: Cannot assign to read only property 'route' of class
        at f (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20551:46)
        at s (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20605:20)
        at /Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20640:153
        at Function.map (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:18323:258)
        at /Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20639:166
        at processQueue (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:5911:339)
        at /Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:5911:634
        at Scope.$eval (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:6472:64)
        at Scope.$digest (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:6393:103)
        at Scope.$apply (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:6547:159)
    Error: Declaration Location
        at window.inject.angular.mock.inject (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:16438:28)
        at Suite.<anonymous> (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20812:60)
        at Object.<anonymous> (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20707:2)
        at __webpack_require__ (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20:30)
        at webpackContext (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:16514:10)
        at Array.forEach (native)
        at Object.<anonymous> (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:54:17)
Chrome 47.0.2526 (Mac OS X 10.11.2) Tag should be able to fetch a list of file tags by UUID FAILED
    TypeError: Cannot assign to read only property 'route' of fetched_tag_1
        at f (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20551:46)
        at s (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20605:20)
        at /Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20640:153
        at Function.map (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:18323:258)
        at /Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20639:166
        at processQueue (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:5911:339)
        at /Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:5911:634
        at Scope.$eval (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:6472:64)
        at Scope.$digest (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:6393:103)
        at Scope.$apply (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:6547:159)
    Error: Declaration Location
        at window.inject.angular.mock.inject (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:16438:28)
        at Suite.<anonymous> (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:23433:62)
        at Object.<anonymous> (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:23425:2)
        at __webpack_require__ (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:20:30)
        at webpackContext (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:16514:10)
        at Array.forEach (native)
        at Object.<anonymous> (/Users/vlcice/artefactual/appraisal-tab/test/tests.webpack.js:54:17)
Chrome 47.0.2526 (Mac OS X 10.11.2): Executed 70 of 70 (2 FAILED) (0.732 secs / 0.675 secs)
```

**Comment by mistydemeo** [comment]
It looks like the failing tests are caused by some sort of interaction of webpack/angular.mocks, but it's not clear to me why only those two tests are failing if so.

**Comment by mistydemeo** [comment]
As a result of moving to ES6, there are also some cleanups I plan to do in a future PR:
- Remove `use strict` statements; ES5 strict mode is equivalent to ES6's default settings.
- Remove IIFEs; webpack's namespacing prevents pollution of global scope.
- Possibly, export specific objects from within parts of the application so that they can be imported as objects from JS modules. (Right now, everything within the appraisal tab is 100% dependent on Angular's module system.)

**Comment by mistydemeo** [comment]
Hoping to merge this soon, and make further changes on top of it.

**Comment by Hwesta** [comment]
:+1:

**Comment by jhsimpson** [comment]
+1

**Pull request merged**
