### PR TITLE
Add SipArrange service

### PR DESCRIPTION
**Pull request by mistydemeo**

### CODE REVIEW

**Comment by mistydemeo** [comment]
I've pushed Base64 encoding and decoding inside the service, so all code interacting with this service provides and receives values as plain strings.

**Comment by mistydemeo** [comment]
Note that a couple of tests are failing right now. This works against the real API; the problem seems to be with mocking REST calls that POST form-encoded data.

**Comment by mistydemeo** [comment]
Fixed the tests.

**Comment by Hwesta** [comment]
:+1:

**Pull request merged**
